name: build

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64_x86
    
    - uses: actions/setup-python@v4
      with:
        cache: 'pip'
        python-version: 'pypy3.x' # 3.9?

    - name: Install meson
      run: pip install meson

    - run: python --version

    - run: choco install ninja


    - name: configure
      run: meson --buildtype=debug bin
    
    - name: compile
      run: meson compile -C bin --load-average=100 --verbose
