name: build

on: 
  push:
    paths:
    - '**.cpp'
    - '**.hpp'
    - '**.c'
    - '**.h'
    - '**.rc'
    - '**.def'
    - '**.lib'
    - '**.dll'
    - '**.build'
    - '**.bmp'
    - '**.png'
    - '**.jpg'
    - '**.webp'
    - '.github/**'
    - 'res/**'
    - 'src/**'
    - 'subprojects/**'
    - '.gitmodules'


jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 'pypy3.9'
        cache: 'pip'

    - name: Install meson and ninja
      run: pypy3 -m pip install -r .github/workflows/requirements.txt

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64_x86

    - name: Configure
      run: meson setup bin --buildtype=debug

    - name: Compile
      run: meson compile -C bin --verbose --load-average=100
    