name: build

on: 
  push:
    paths:
    - '.github/**'
    - 'res/**'
    - 'src/**'
    - 'subprojects/**'
    - '.gitmodules'


jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    
    - uses: actions/setup-python@v4
      with:
        python-version: 'pypy3.9'
        cache: 'pip'

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64_x86
    
    - name: Configure and compile
      uses: BSFishy/meson-build@v1
      with:
        action: compile
        directory: bin
        setup-options: --buildtype=debug
        options: --verbose --load-average=100
